### ISSUE TITLE
Browser panel opens with variable names instead of values

### ISSUE THREAD

**Issue by Zzmobie** [CS2103AUG2017-F11-B1/main#69]
Can quite clearly see "$first $group, $phone, $address, $email" fields of the javafx file on first load.

**Comment by syy94** [comment]
Sorry for the inconvenience but we were planning do a proper UI update after v1.4 to finalize what the application can do and plan for the optimal UI to best serve the user's needs.

**Comment by syy94** [comment]
Fixed in https://github.com/CS2103AUG2017-F11-B1/main/pull/86
