### ISSUE TITLE
Sort command has inappropriate parameters

### ISSUE THREAD

**Issue by Zzmobie** [CS2103AUG2017-F11-B1/main#71]
It is rather unusual to have the parameters be [/n], [/p]. Using the field tags to be your parameter seems inappropriate, it should probably be just "phone, or name". In the current way your user guide describes it, you can have more than one of these parameters, but your sort function does not support this. Consider using a "TYPE" parameter instead, which can be any of "/n","/p" or any of the other sorting parameters

**Comment by sofarsophie** [comment]
Sort command usage guide updated in PR #87.
Our app has unified all functions to use the field tags, for better usability. We understand the pros and cons of using field tags (as opposed to 'phone' or 'address' etc). We will discuss your suggestion and may place it in our 1.5 > plans! :) Thanks for the comment.
