### ISSUE TITLE
Add command does not work

### ISSUE THREAD

**Issue by Zzmobie** [CS2103AUG2017-F11-B1/main#74]
The example add command does not work. 
![image](https://user-images.githubusercontent.com/31027322/32363058-4eee94f4-c0a8-11e7-9435-960356d950fd.png)

**Comment by Zzmobie** [comment]
Even very basic commands do not work, has the add command description not been edited with new fields?
Even a command like: 
add n/lawrence p/999 e/bob@gmail.com a/bob street
is not accepted

**Comment by syy94** [comment]
![image](https://user-images.githubusercontent.com/28534459/32367746-26d53dc2-c0be-11e7-9fad-0912fb21dfc1.png)

![image](https://user-images.githubusercontent.com/28534459/32367820-7ce8a5aa-c0be-11e7-9fbd-8eb3f8ec2d52.png)


AddCommand strictly requires the prefixes `n/` (name) and `g/` (group) as stated in both our web and in-app user guide. Sorry for not making the documentation more clear and we will try to improve them in the next update.

**Comment by syy94** [comment]
![image](https://user-images.githubusercontent.com/28534459/32367895-c1e1fc42-c0be-11e7-8966-48efecb3683f.png)

Plus in your screenshot I noticed that there is no space between your `g/` (group) prefix and your `a/` (address) prefix. As such, the program will deny adding this person as group only accepts alphanumeric values characters and spaces as stated by the ResultDisplay.

I understand that long commands such as this is error-prone therefore we shall plan for autocomplete in V2.0.

Please tell us if the problem still persist, we will be more than happy to debug and perfect our application.

**Comment by Zzmobie** [comment]
I copied that command from your example command in the case of an erroneous command. It's kinda supposed to work since it's an example provided by you.

**Comment by syy94** [comment]
Thanks for bringing the mistake up. Will fix in the next update.
