### ISSUE TITLE
The correct example command is not shown upon wrong command input

### ISSUE THREAD

**Issue by TanYikai** [CS2103AUG2017-F11-B1/main#75]
For example if i input "add n/ " only, which is an invalid command, the example of the correct command format should be displayed at the bottom of the command input line.

**Comment by Zzmobie** [comment]
Yea the correct command format isn't given. The add command format has to have a group field, but the description in the application itself hasn't been updated to necessitate that. 

The example given doesn't work either, since their group field has a "/" character that they do not allow for.

**Comment by syy94** [comment]
![image](https://user-images.githubusercontent.com/28534459/32368162-d7cdd3ae-c0bf-11e7-861f-f87f3db63184.png)

Hi i downloaded the jar file and tried to re-create this bug and I was unable to recreate it. Could you kindly give me more details of how you arrived at this problem and if possible upload the log file together with the steps to recreate this problem.

**Comment by Zzmobie** [comment]
I'm pretty sure they just thought that when the display on the left turns white = addressbook deleted. I'm quite sure there is no bug here.

**Comment by syy94** [comment]
I noticed that our example is missing a space. This will be rectified in our next update.

**Comment by syy94** [comment]
Ok noted with thanks! @Zzmobie
