### ISSUE TITLE
List command will trigger unexpected clearing of addressbook

### ISSUE THREAD

**Issue by TanYikai** [CS2103AUG2017-F11-B1/main#76]
When "list n" or "list anything" is input, the whole adressbook is cleared

**Comment by Juxarius** [comment]
yea mine got cleared as well

**Comment by Zzmobie** [comment]
I don't think it's cleared, I can't replicate the same behavior. I think it's just that it displays the empty list since no search results are found. Try typing "list all" after list n and it should work.

**Comment by syy94** [comment]
What @Zzmobie says is correct this is the default action that came with the AB4 will try to improve it in the next update such that empty lists are more oblivious. Thank you for bringing this up.
