### ISSUE TITLE
Password is stored as a plaintext file. Password isn't hashed.

### ISSUE THREAD

**Issue by Zzmobie** [CS2103AUG2017-F11-B1/main#77]
I forgot my password and couldn't login, but since the password was stored as plaintext, I could just look for it in the appropriate folder.

**Comment by Zzmobie** [comment]
Probably should also explain what happens when a password is put in place in the user guide.

**Comment by syy94** [comment]
Enhancement v2.0 Password Recovery https://github.com/CS2103AUG2017-F11-B1/main/issues/83

**Comment by syy94** [comment]
Basic Password Encryption and description added. https://github.com/CS2103AUG2017-F11-B1/main/pull/94
