### ISSUE TITLE
Suggestion: can enhance add command 

### ISSUE THREAD

**Issue by TanYikai** [CS2103AUG2017-F11-B1/main#81]
Add command can be made more comprehensive by enabling the addition of person even when not all the information is given. Eg, add n/john will now be a valid add command instead of having to key in add n/john p/21443153 e/email@this.com a/Block 432 shinglee street g/acd ...

**Comment by syy94** [comment]
Hi the current bare minimum of 2 prefixes are required to create a person, `n/` (name) and `g/` (group), and it is part of our design that the group should be required to add a person. 

We value your input and we will discuss this and improve this command in future updates. Thank you.
