### ISSUE TITLE
[Acceptance Testing] Hashing password key

### ISSUE THREAD

**Issue by Choony93** [CS2103AUG2017-F11-B1/main#88]
Password currently stored as plain text. Can try the MessageDigest library to hash it, then store the hased string. Then whenever user tries to set new password, hash the user's new input password and see if the both hash is the same. 

Can try:
MessageDigest digest = MessageDigest.getInstance("SHA-256");
byte[] hash = digest.digest(text.getBytes(StandardCharsets.UTF_8)); //text is the user input string
String encoded = Base64.getEncoder().encodeToString(hash);

More information can be found here:
https://howtodoinjava.com/security/how-to-generate-secure-password-hash-md5-sha-pbkdf2-bcrypt-examples/ @syy94

**Comment by syy94** [comment]
Oh nice I was planning to try using Base64

https://stackoverflow.com/questions/19743851/base64-java-encode-and-decode-a-string

This one looks better. Thx

**Comment by syy94** [comment]
Completed password hashing @https://github.com/CS2103AUG2017-F11-B1/main/pull/94
